---
title: "matUtils_introduce_analysis"
author: "Philip Ashton"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Imports

```{r imports}

library(readr)
library(dplyr)
library(scales)
library(stringr)
library(ggplot2)
library(patchwork)
library(lubridate)
library(kableExtra)

```


## Sources

```{r}
source("utils.R")
```

## File paths

```{r filepaths}

malawi_per_sample_intro_handle <- "/Users/flashton/Dropbox/COVID/AAP_introductions/results/2022.12.02/malawian_introductions.excl_mwi_dups.txt"
national_cases_handle <- "/Users/flashton/Dropbox/COVID/our_world_in_data/2022.12.05/owid-covid-data.csv"
restrictions_handle <- "/Users/flashton/Dropbox/COVID/our_world_in_data/2022.12.05/international-travel-covid.csv"

```

## vars to set

```{r}

vocs_to_plot <- list("20H (Beta,V2)", "20I (Alpha,V1)", "21A (Delta)", "21I (Delta)", "21J (Delta)", "21K (Omicron)", "21L (Omicron)", "22A (Omicron)", "22B (Omicron)")
countries_to_include <- c("MWI", "KEN", "ZAF", "VNM", "THA", "IDN", "KHM")

```

## Size distribtion by VOC

```{r}

plot_size_distribution_by_VOC_point <- function(per_sample_intros){
  distinct_intros <- distinct(per_sample_intros, introduction_node, .keep_all = TRUE)
  return(distinct_intros)
}

plot_size_distribution_by_VOC <- function(distinct_intros){
  df_labels <- distinct_intros %>% group_by(voc_for_plots) %>% summarise(n = paste0("n = ",  n()))
  # will need to change the 200 below to something larger for countries with larger cluster sizes.
  p <- ggplot(distinct_intros, aes(x = voc_for_plots, y = cluster_size, colour = voc_for_plots)) +
    geom_jitter(alpha = 0.4, width = 0.3) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    stat_summary(fun = "median", colour = "black", shape = 95) +
    geom_label(data = df_labels, aes(y = Inf, label = n), label.size = 0, fill = NA, vjust = 1) +
    scale_y_log10(limits = c(1, max(distinct_intros$cluster_size) + 200))
  print(p)
  #print(q)
  return(distinct_intros)
}

```

## stats on distinct intros

```{r}
basic_stats_on_distinct_intros <- function(distinct_intros){
  group_by(distinct_intros, voc_for_plots) %>% summarise(number_clusters = n(), number_genomes = sum(cluster_size), mean_cluster_size = mean(cluster_size, na.rm = TRUE), sd_cluster_size = sd(cluster_size, na.rm = TRUE), median_cluster_size = median(cluster_size, na.rm = TRUE), IQR_cluster_size = IQR(cluster_size, na.rm = TRUE)) %>% kbl() %>% kable_styling()
}
```



## main function

If kruskal.test p-value is <0.05, then need to do pairwise wilcoxon rank sum tests.

```{r fig.width=14, fig.height=10}

#national_cases <- read_in_national_case_numbers(national_cases_handle, countries_to_include)
#per_sample_intros <- read_in_per_sample_intros(malawi_per_sample_intro_handle, vocs_to_plot)
#restrictions <- read_in_restrictions(restrictions_handle, countries_to_include)
#View(intros)
#distinct_intros <- distinct(per_sample_intros, introduction_node, .keep_all = TRUE)
#plot_size_distribution_by_VOC(distinct_intros)
#basic_stats_on_distinct_intros(distinct_intros)
#print(kruskal.test(cluster_size ~ voc_for_plots, data = distinct_intros))
#make_overall_plot(per_sample_intros, "20H (Beta,V2)", national_cases, restrictions, "MWI")




national_cases <- read_in_national_case_numbers(national_cases_handle, countries_to_include)
View(national_cases)
restrictions <- read_in_restrictions(restrictions_handle, countries_to_include)

run_main <- function(per_sample_intro_handle, country_iso, national_cases, vocs_to_plot, restrictions){
  #print(per_sample_intro_handle)
  #print(country_iso)
  per_sample_intros <- read_in_per_sample_intros(per_sample_intro_handle, vocs_to_plot)
  View(per_sample_intros)
  distinct_intros <- distinct(per_sample_intros, introduction_node, .keep_all = TRUE)
  plot_size_distribution_by_VOC(distinct_intros)
  basic_stats_on_distinct_intros(distinct_intros)
  print(kruskal.test(cluster_size ~ voc_for_plots, data = distinct_intros))
  #make_overall_plot(per_sample_intros, "20H (Beta,V2)", national_cases, restrictions, "MWI")
  View(national_cases)
  lapply(vocs_to_plot, make_overall_plot, per_sample_intros = per_sample_intros, national_cases = national_cases, restrictions = restrictions, country_iso = country_iso)
}

countries_to_plot <- c("MWI", "KEN")
per_sample_intro_handles <- c("/Users/flashton/Dropbox/COVID/AAP_introductions/results/2022.12.02/malawian_introductions.excl_mwi_dups.txt", "/Users/flashton/Dropbox/COVID/AAP_introductions/results/2022.12.02/kenyan_introductions.txt")
#run_main(national_cases, malawi_per_sample_intro_handle, vocs_to_plot, restrictions, "MWI")

# apply converts data frame to matrix, so can't use it
#mapply(run_main, per_sample_intro_handles, countries_to_plot, national_cases = national_cases, vocs_to_plot = vocs_to_plot, restrictions = restrictions)

run_main("/Users/flashton/Dropbox/COVID/AAP_introductions/results/2022.12.02/malawian_introductions.excl_mwi_dups.txt", "MWI", national_cases = national_cases, vocs_to_plot = vocs_to_plot, restrictions = restrictions)
run_main("/Users/flashton/Dropbox/COVID/AAP_introductions/results/2022.12.02/kenyan_introductions.txt", "KEN", national_cases = national_cases, vocs_to_plot = vocs_to_plot, restrictions = restrictions)

```

## main plots

Todo:

1. Do for each genotype, for each country (need to do the matUtils introduce as well)
2. Name the nodes according the matUtils ranking

```{r fig.width=14, fig.height=10}

#make_overall_plot(per_sample_intros, "20H (Beta,V2)", national_cases, restrictions, "MWI")
#vocs_to_plot <- list("20H (Beta,V2)")
lapply(vocs_to_plot, make_overall_plot, per_sample_intros = per_sample_intros, national_cases = national_cases, restrictions = restrictions, country_iso = "MWI")

```
